name: Build And Upload Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - name: Install dependencies (with workspaces)
        run: pnpm install --frozen-lockfile --prefer-offline --recursive
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
